_target_: fusion_bench.method.mingle.consensus_ta.ContinualConsensusTAForCLIP

# Scaling factor $\lambda$
scaling_factor: 0.1
lmda: 0.2
k: 2
# List of keys to remove from the state dict, default is empty
remove_keys: []

# shuffle the order of the models
shuffle_order: true
# the random seed to use
seed: null
# save the merged model on every step
save_on_every_step: false
# evaluate the merged model on every step
evaluate_on_every_step: false