_target_: fusion_bench.method.mingle.magmax.MagMaxForCLIP

# Scaling factor $\lambda$
scaling_factor: 0.5
# List of keys to remove from the state dict, default is empty
remove_keys: []
# Function to merge the models, default is sum. Options are 'sum', 'mean', and 'max'

# shuffle the order of the models
shuffle_order: true
# the random seed to use
seed: 42
# save the merged model on every step
save_on_every_step: false
# evaluate the merged model on every step
evaluate_on_every_step: true
