defaults:
  - CLIPVisionModelTaskPool@: _template
  - /dataset/image_classification/test@test_datasets:
        - aircraft
        - caltech101
        - cifar100
        - dtd
        - eurosat
        - oxford_flowers102
        - food101
        - mnist
        - oxford-iiit-pet
        - stanford-cars
        - sun397